<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
		<AssemblyName>filo</AssemblyName>
		<RootNamespace>Filociraptor</RootNamespace>
		<Nullable>enable</Nullable>
		<ImplicitUsings>true</ImplicitUsings>
		<PublishAot>true</PublishAot>
		<InvariantGlobalization>true</InvariantGlobalization>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<IsAotCompatible>true</IsAotCompatible>
		<ApplicationManifest>app.manifest</ApplicationManifest>
		<ApplicationIcon>Filociraptor.ico</ApplicationIcon>
		<WindowsSdkPackageVersion>10.0.26100.57</WindowsSdkPackageVersion>
		<Platforms>x64;ARM64;x86</Platforms>

		<Title>Filociraptor</Title>
		<Company>Simon Mourier</Company>
		<Authors>Simon Mourier</Authors>
		<Product>Filociraptor</Product>
		<AssemblyTitle>Filociraptor</AssemblyTitle>
		<Description>A fast Windows file manager in C#, Direct2D and NativeAOT.</Description>
		<Copyright>Copyright (C) 2024-$([System.DateTime]::UtcNow.ToString("yyyy")) Simon Mourier. All rights reserved.</Copyright>

		<ProductVersion>1.1.0</ProductVersion>
		<Version>1.1.0</Version>
		<FileVersion>1.1.0</FileVersion>
		<InformationalVersion>1.1.0</InformationalVersion>
		<SourceRevisionId>$([System.DateTime]::UtcNow.ToString("yyyyMMddHHmmss"))</SourceRevisionId>
	</PropertyGroup>

	<ItemGroup>
		<Content Include="Filociraptor.ico" />
	</ItemGroup>

	<ItemGroup>
		<EmbeddedResource Update="Res.resx">
			<Generator>ResXFileCodeGenerator</Generator>
			<LastGenOutput>Res.Designer.cs</LastGenOutput>
		</EmbeddedResource>
		<Compile Update="Res.Designer.cs">
			<DesignTime>True</DesignTime>
			<AutoGen>True</AutoGen>
			<DependentUpon>Res.resx</DependentUpon>
		</Compile>
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="DirectNAot" Version="1.6.5" />
		<PackageReference Include="DirectNAot.Extensions" Version="1.6.5" />
		<PackageReference Include="ShellN" Version="1.0.8" />
		<PackageReference Include="WicNetCore" Version="1.9.3" />
		<PackageReference Include="ShellN.Extensions" Version="1.0.8" />
	</ItemGroup>

	<ItemGroup>
		<Using Include="DirectN" />
		<Using Include="DirectN.Extensions" />
		<Using Include="DirectN.Extensions.Com" />
		<Using Include="DirectN.Extensions.Utilities" />
		<Using Include="Filociraptor.Diagnostics" />
		<Using Include="Filociraptor.FileSystem" />
		<Using Include="Filociraptor.Rendering" />
		<Using Include="Filociraptor.Shell" />
		<Using Include="System.Collections.Concurrent" />
		<Using Include="System.Diagnostics" />
		<Using Include="System.Diagnostics.CodeAnalysis" />
		<Using Include="System.IO.Enumeration" />
		<Using Include="System.Resources" />
		<Using Include="System.Runtime.CompilerServices" />
		<Using Include="System.Runtime.InteropServices" />
		<Using Include="System.Runtime.InteropServices.Marshalling" />
		<Using Include="System.Text" />
		<Using Include="System.Threading.Channels" />
	</ItemGroup>

</Project>
