//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Filociraptor {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Res {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Res() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Filociraptor.Res", typeof(Res).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modified.
        /// </summary>
        internal static string ColumnModified {
            get {
                return ResourceManager.GetString("ColumnModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string ColumnName {
            get {
                return ResourceManager.GetString("ColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        internal static string ColumnSize {
            get {
                return ResourceManager.GetString("ColumnSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string ColumnType {
            get {
                return ResourceManager.GetString("ColumnType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CD Drive.
        /// </summary>
        internal static string DriveCdRom {
            get {
                return ResourceManager.GetString("DriveCdRom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  free of .
        /// </summary>
        internal static string DriveFreeOf {
            get {
                return ResourceManager.GetString("DriveFreeOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local Disk.
        /// </summary>
        internal static string DriveLocal {
            get {
                return ResourceManager.GetString("DriveLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network Drive.
        /// </summary>
        internal static string DriveNetwork {
            get {
                return ResourceManager.GetString("DriveNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to not ready.
        /// </summary>
        internal static string DriveNotReady {
            get {
                return ResourceManager.GetString("DriveNotReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drive.
        /// </summary>
        internal static string DriveOther {
            get {
                return ResourceManager.GetString("DriveOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RAM Disk.
        /// </summary>
        internal static string DriveRam {
            get {
                return ResourceManager.GetString("DriveRam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removable Disk.
        /// </summary>
        internal static string DriveRemovable {
            get {
                return ResourceManager.GetString("DriveRemovable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unknown size.
        /// </summary>
        internal static string DriveUnknownSize {
            get {
                return ResourceManager.GetString("DriveUnknownSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder.
        /// </summary>
        internal static string Folder {
            get {
                return ResourceManager.GetString("Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  B.
        /// </summary>
        internal static string UnitByte {
            get {
                return ResourceManager.GetString("UnitByte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  GB.
        /// </summary>
        internal static string UnitGigaByte {
            get {
                return ResourceManager.GetString("UnitGigaByte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  KB.
        /// </summary>
        internal static string UnitKiloByte {
            get {
                return ResourceManager.GetString("UnitKiloByte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  MB.
        /// </summary>
        internal static string UnitMegaByte {
            get {
                return ResourceManager.GetString("UnitMegaByte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  TB.
        /// </summary>
        internal static string UnitTeraByte {
            get {
                return ResourceManager.GetString("UnitTeraByte", resourceCulture);
            }
        }
    }
}
