//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Filociraptor {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Res {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Res() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Filociraptor.Res", typeof(Res).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acrylic.
        /// </summary>
        internal static string BackdropAcrylic {
            get {
                return ResourceManager.GetString("BackdropAcrylic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mica.
        /// </summary>
        internal static string BackdropMica {
            get {
                return ResourceManager.GetString("BackdropMica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string BackdropNone {
            get {
                return ResourceManager.GetString("BackdropNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modified.
        /// </summary>
        internal static string ColumnModified {
            get {
                return ResourceManager.GetString("ColumnModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string ColumnName {
            get {
                return ResourceManager.GetString("ColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        internal static string ColumnSize {
            get {
                return ResourceManager.GetString("ColumnSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string ColumnType {
            get {
                return ResourceManager.GetString("ColumnType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CD Drive.
        /// </summary>
        internal static string DriveCdRom {
            get {
                return ResourceManager.GetString("DriveCdRom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  free of .
        /// </summary>
        internal static string DriveFreeOf {
            get {
                return ResourceManager.GetString("DriveFreeOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local Disk.
        /// </summary>
        internal static string DriveLocal {
            get {
                return ResourceManager.GetString("DriveLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network Drive.
        /// </summary>
        internal static string DriveNetwork {
            get {
                return ResourceManager.GetString("DriveNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to not ready.
        /// </summary>
        internal static string DriveNotReady {
            get {
                return ResourceManager.GetString("DriveNotReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drive.
        /// </summary>
        internal static string DriveOther {
            get {
                return ResourceManager.GetString("DriveOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RAM Disk.
        /// </summary>
        internal static string DriveRam {
            get {
                return ResourceManager.GetString("DriveRam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removable Disk.
        /// </summary>
        internal static string DriveRemovable {
            get {
                return ResourceManager.GetString("DriveRemovable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unknown size.
        /// </summary>
        internal static string DriveUnknownSize {
            get {
                return ResourceManager.GetString("DriveUnknownSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder.
        /// </summary>
        internal static string Folder {
            get {
                return ResourceManager.GetString("Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window material.
        /// </summary>
        internal static string SettingBackdrop {
            get {
                return ResourceManager.GetString("SettingBackdrop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear the list.
        /// </summary>
        internal static string SettingClearRecentFolders {
            get {
                return ResourceManager.GetString("SettingClearRecentFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font.
        /// </summary>
        internal static string SettingFont {
            get {
                return ResourceManager.GetString("SettingFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font size.
        /// </summary>
        internal static string SettingFontSize {
            get {
                return ResourceManager.GetString("SettingFontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image preview.
        /// </summary>
        internal static string SettingImagePreview {
            get {
                return ResourceManager.GetString("SettingImagePreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing yet.
        /// </summary>
        internal static string SettingNoRecentFolders {
            get {
                return ResourceManager.GetString("SettingNoRecentFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to off.
        /// </summary>
        internal static string SettingOff {
            get {
                return ResourceManager.GetString("SettingOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open archives as files.
        /// </summary>
        internal static string SettingOpenArchivesAsFiles {
            get {
                return ResourceManager.GetString("SettingOpenArchivesAsFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to beside the program.
        /// </summary>
        internal static string SettingPortable {
            get {
                return ResourceManager.GetString("SettingPortable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent folders.
        /// </summary>
        internal static string SettingRecentFolders {
            get {
                return ResourceManager.GetString("SettingRecentFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove the ones that are gone.
        /// </summary>
        internal static string SettingRemoveMissingFolders {
            get {
                return ResourceManager.GetString("SettingRemoveMissingFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in your profile.
        /// </summary>
        internal static string SettingRoaming {
            get {
                return ResourceManager.GetString("SettingRoaming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings file.
        /// </summary>
        internal static string SettingSettingsFile {
            get {
                return ResourceManager.GetString("SettingSettingsFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Square thumbnails.
        /// </summary>
        internal static string SettingSquareThumbnails {
            get {
                return ResourceManager.GetString("SettingSquareThumbnails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text colour.
        /// </summary>
        internal static string SettingTextColor {
            get {
                return ResourceManager.GetString("SettingTextColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        internal static string SettingTheme {
            get {
                return ResourceManager.GetString("SettingTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thumbnail spacing.
        /// </summary>
        internal static string SettingThumbnailSpacing {
            get {
                return ResourceManager.GetString("SettingThumbnailSpacing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thumbnail titles.
        /// </summary>
        internal static string SettingThumbnailTitles {
            get {
                return ResourceManager.GetString("SettingThumbnailTitles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrap thumbnail titles.
        /// </summary>
        internal static string SettingWrapThumbnailTitles {
            get {
                return ResourceManager.GetString("SettingWrapThumbnailTitles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        internal static string ThemeDark {
            get {
                return ResourceManager.GetString("ThemeDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        internal static string ThemeLight {
            get {
                return ResourceManager.GetString("ThemeLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use system.
        /// </summary>
        internal static string ThemeSystem {
            get {
                return ResourceManager.GetString("ThemeSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  B.
        /// </summary>
        internal static string UnitByte {
            get {
                return ResourceManager.GetString("UnitByte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  GB.
        /// </summary>
        internal static string UnitGigaByte {
            get {
                return ResourceManager.GetString("UnitGigaByte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  KB.
        /// </summary>
        internal static string UnitKiloByte {
            get {
                return ResourceManager.GetString("UnitKiloByte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  MB.
        /// </summary>
        internal static string UnitMegaByte {
            get {
                return ResourceManager.GetString("UnitMegaByte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  TB.
        /// </summary>
        internal static string UnitTeraByte {
            get {
                return ResourceManager.GetString("UnitTeraByte", resourceCulture);
            }
        }
    }
}
